# Generated by Django 3.2.12 on 2022-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500, verbose_name='Menssagem')),
                ('data_2', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Recebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_3', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data')),
                ('contato_2', models.CharField(max_length=500, null=True, verbose_name='Confirmar tel.:')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doacao', models.CharField(max_length=255, verbose_name='Doação')),
                ('contato', models.CharField(max_length=255, null=True, verbose_name='Telefone para contato')),
                ('endereco', models.CharField(max_length=255, null=True, verbose_name='Endereço para entrega')),
                ('obs', models.TextField(blank=True, verbose_name='Observação')),
                ('data_1', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='users/%Y/%m/%d/', verbose_name='Upload imagem')),
            ],
        ),
    ]
